### ISSUE TITLE
option to not restore workspace

### ISSUE THREAD

**Issue by APTISteve** [khimaros/smart-auto-move#21] opened 2022-02-11 00:00 UTC
I am using your extension because I have a multi monitor setup and this keeps things on the right monitor. however it is also insanely annoying when it restores apps to different workspaces. I feel an option to restore to a location regardless of workspace would be great. In fact it would make this extension perfect. 
so to make it clear what I am asking...
.. an option that switches from the current operation to only restoring position without concern for workspace.
.. this mean with that option on the window is not put on a particular workspace but instead just on the current workspace but in the position it would have been on the original workspace.

**Comment by khimaros** [comment] 2022-02-19 18:36
duplicate of https://github.com/khimaros/smart-auto-move/issues/7

**Closed by khimaros** 2022-02-19 18:36 UTC
Labels: duplicate, enhancement
