### ISSUE TITLE
Laggy desktop when extension is enabled

### ISSUE THREAD

**Issue by ChrisLauinger77** [khimaros/smart-auto-move#49] opened 2024-04-22 19:00 UTC
Today I got the update from EGO which supports GNOME 45/46.
There is already a comment on EGO:
![Bildschirmfoto vom 2024-04-22 20-57-19](https://github.com/khimaros/smart-auto-move/assets/3518684/da616023-c863-4b05-97eb-bf1deb093fe5)

When I enable debuglog the extension cyclicly spams the log with messages.
Video playback lags as well as playing games. Every 1-2s it video / frames stutter.
```
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() christian@debian:~ false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Erweiterungen false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Smart Auto Move true 4
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() null true 15
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Bildschirmfotos false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() conky (debian) true 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Steam false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() ESL_DOTA2 - Dota 2 - LIVE: Xtreme Gaming vs. OG Esports - ESL One Birmingham 2024 - Group B - VLC media player false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Laggy desktop when extension is enabled · Issue #49 · khimaros/smart-auto-move – Mozilla Firefox false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() christian@debian:~ false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Erweiterungen false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Smart Auto Move true 4
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() null true 15
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Bildschirmfotos false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() conky (debian) true 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Steam false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() ESL_DOTA2 - Dota 2 - LIVE: Xtreme Gaming vs. OG Esports - ESL One Birmingham 2024 - Group B - VLC media player false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Laggy desktop when extension is enabled · Issue #49 · khimaros/smart-auto-move – Mozilla Firefox false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() christian@debian:~ false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Erweiterungen false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Smart Auto Move true 4
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() null true 15
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Bildschirmfotos false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() conky (debian) true 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Steam false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() ESL_DOTA2 - Dota 2 - LIVE: Xtreme Gaming vs. OG Esports - ESL One Birmingham 2024 - Group B - VLC media player false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Laggy desktop when extension is enabled · Issue #49 · khimaros/smart-auto-move – Mozilla Firefox false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() christian@debian:~ false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Erweiterungen false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Smart Auto Move true 4
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() null true 15
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Bildschirmfotos false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() conky (debian) true 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Steam false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() ESL_DOTA2 - Dota 2 - LIVE: Xtreme Gaming vs. OG Esports - ESL One Birmingham 2024 - Group B - VLC media player false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() Laggy desktop when extension is enabled · Issue #49 · khimaros/smart-auto-move – Mozilla Firefox false 0
Apr 22 21:01:14 debian gnome-shell[2565]: [smart-auto-move] shouldSkipWindow() christian@debian:~ false 0
```

**Comment by khimaros** [comment] 2024-04-23 05:12
acknowledged, i'm able to reproduce this with GNOME OS nightly.

i thought i noticed something but chalked it up to being in a virtual machine.

investigating now.

**Comment by khimaros** [comment] 2024-04-23 05:30
okay, the issue is that when sync or save frequency are < 1000, it rounds down to 0 in the call to GLib.add_timeout_seconds() which results in syncing/saving continuously. short term fix is to bump the value to 1000 or higher. i'm working on a proper fix.

**Comment by khimaros** [comment] 2024-04-23 05:38
indeed, this was caused by a rounding error in calls to `GLib.timeout_add_seconds()` which i've resolved by switching back to `GLib.timeout_add()`. breakfix release is under review by GNOME folks.

**Closed** 2024-04-23 06:03 UTC
Labels: bug, pending-review
