### ISSUE TITLE
[BUG] unable to open settings

### ISSUE THREAD

**Issue by Gtosta96** [khimaros/smart-auto-move#29] opened 2022-04-25 17:07 UTC
Hey, first things first, thanks for such a great extension!
Although the extension is working I'm unable to open the settings, this is what I get.

Do you know what should I do to overcome this situation?

P.S: I'm running it on Linux:
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```

----

The settings of extension smart-auto-move@khimaros.com had an error:
```
Gtk.BuilderError: /home/gabriel-tosta/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/ui/prefs-gtk4.ui:22:33 Invalid property: GtkNotebook.focusable
```

Stack trace:
```
buildPrefsWidget@/home/gabriel-tosta/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/prefs.js:41:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Thanks! =)

**Comment by lordyersinia** [comment] 2022-05-11 23:11
Getting the same error on:

Ubuntu 20.04.2 LTS x86_64
5.13.0-41-generic

The settings of extension smart-auto-move@khimaros.com had an error:
```
Gtk.BuilderError: /home/chase/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/ui/prefs-gtk4.ui:22:33 Invalid property: GtkNotebook.focusable
```

Stack trace:
```
buildPrefsWidget@/home/chase/.local/share/gnome-shell/extensions/smart-auto-move@khimaros.com/prefs.js:41:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by lordyersinia** [comment] 2022-05-15 19:56
Upgraded to Ubuntu 22.04 (Gnome 42) 

Seems to work fine now!

**Comment by khimaros** [comment] 2022-06-12 22:52
duplicate of https://github.com/khimaros/smart-auto-move/issues/24

**Closed by khimaros** 2022-06-12 22:52 UTC
Labels: duplicate
