### ISSUE TITLE
'!window->override_redirect' failed spam

### ISSUE THREAD

**Issue by terencode** [khimaros/smart-auto-move#3] opened 2022-01-09 13:49 UTC
After enabling the extension, my log is spammed with the following message : 

`meta_window_move_resize_frame: assertion '!window->override_redirect' failed`
and 
`meta_window_change_workspace: assertion '!window->override_redirect' failed`
I'm on Archlinux, GNOME 41.2.

**Comment by khimaros** [comment] 2022-01-10 05:04
hi @terencode thank you for the report. so far i have not been able to reproduce this. are you running on X11 or Wayland? do you have any other extensions enabled?

**Comment by terencode** [comment] 2022-01-10 13:18
Hey khimaros, 
I'm on X11. I had other extensions installed but I disabled them all except this extension and I could still reproduce after a restart of the shell.
However, now that I installed the latest version, I only see a few lines after enabling the extension and nothing else.

**Comment by khimaros** [comment] 2022-01-12 02:39
that's great to hear. closing this for now as i cannot reproduce and it seems to be resolved for you. thank you for the report.

**Closed by khimaros** 2022-01-12 02:39 UTC
Labels: bug, question

**Comment by terencode** [comment] 2022-01-29 14:40
Nevermind, I enabled this extension again to try out v10 and I get the same problem...
